# Generated by Django 6.0.3 on 2026-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_batch_size_profile_enabled_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymizationhistory',
            name='entities',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
