# Generated by Django 6.0.3 on 2026-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anonymizationhistory_entities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymizationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История анонимизации', 'verbose_name_plural': 'История анонимизаций'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provider',
        ),
        migrations.AlterField(
            model_name='profile',
            name='config_yaml',
            field=models.TextField(blank=True, default='', help_text='YAML конфигурация анонимизаторов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enabled_labels',
            field=models.TextField(blank=True, default='[]', help_text='JSON-список включенных меток'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
